### ISSUE TITLE
Binds showing before js load

### ISSUE THREAD

**Issue by DeadpoolPancakes** [Naylorweb/Plugintestings#1]
{{proeprty.id}} showing before data as page is loaded but js has not

**Comment by DeadpoolPancakes** [comment]
possible to use a delay to prevent this, look at munro lock website for example

**Comment by jcripley1992** [comment]
usually just have the body or main part of page set as "display:none;" then javascript timer after half a second to then change the CSS to show or change CSS to display:inline and show the content, the angular JS bindings are usually processed before the change and it looks like a nice animated load is using CSS 'transition' for the style change.

**Comment by DeadpoolPancakes** [comment]
Will add this suggestion to documentation

**Comment by DeadpoolPancakes** [comment]
closing as new issue put in for it to be added to documentation
