### ISSUE TITLE
Code not essential

### ISSUE THREAD

**Issue by jcripley1992** [Naylorweb/Plugintestings#2]
some of the parts in "full details" Controller likely need to be removed. e.g.

$scope.Images - slides section - Line 228 to Line 246

is code for Gallery Carousel Slide functionality for Bootstrap ui.bootstrap include code

used on "munrolock" Wordpress Site, can be found online, second part of that section is for have clickable Thumbnails to link with the slides that the Carousel is showing/moving through

up to you !

**Comment by DeadpoolPancakes** [comment]
Uploaded new version of the JS file without this comment and less dependencies. Only needs angular santize now.

Closing this as no complete
